### ISSUE TITLE
How to run autofocus at the right moment?

### ISSUE THREAD

**Issue by nicost** [micro-manager/AcqEngJ#117]
In Micro-Manager, autofocus during an MDA runs after the XY stage and other stages in the position list have been moved in place, but before the Z drive is moved to the first position of a z stacks.  AcqEngJ does not have a logical place for this.  The hook "Before_Hardware" execute before all stages are moved (hence is not applicable), but the hook "AFTER_HARDWARE" executes after all devices (including the drive used for the z stack) is moved to its start position.  

Before taking into consideration other drives in the position list, I solved this by moving the XY stage inside the Autofocus Hook function.  The second move of the XY stage inside the Engine function `prepareHardware` was immaterial, but this same trick does not work for other Z drives, the `prepareHardware` function moves them back to what is now the wrong position.  

I could of course, handle all the hardware manipulation inside my own code, but seems to defeat the purpose of the Engine.  

Is there a simple solution?  The only one I see now is to not add stagepositions to events, but rather execute these in a BEFORE_HARDWARE hook function.

**Comment by henrypinkard** [comment]
I think you could:

- As you say, handle all the hardware in your own code. Messy, but you still get handling of the camera/saving/metadata etc from the engine compared to doing everthing from scratch
- As you say, exclude stage positions from events
- Add a new type of hook function that runs in the place that you need it to run

The correct long terms solution in my opinion is to add another layer of configuration to the sequence of hardware things that need to happen, but this is a feature for an entirely new version

**Comment by nicost** [comment]
I'll try adding a new hook.  That seems least intrusive and most in-line with the design of the whole thing.

Question: when adding a HOOK in AcquisitionAPI.java, can I change the numbering of the existing hooks (so that they are order logically), or should I add it as a new number?  In other words, does anyone rely on the numbers, or does everyone use the symbols?

**Comment by henrypinkard** [comment]
Good question. Looks like pycromanager [uses the symbols](https://github.com/micro-manager/pycro-manager/blob/7587ed1873708d46667b6ef7ed7599da7245e089/pycromanager/acquisition/java_backend_acquisitions.py#L489), so I'd be surprised if anyone uses the numbers. Should be fine to change

**Comment by nicost** [comment]
Addressed in #118
