### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by nicost** [micro-manager/AcqEngJ#31]
Some more documentation of this engine would be nice.  I just started looking at the api to figure out how to send it a "recipe" of a desired acquisition (for instance, a time lapse with a z-stack in two channels at each time point), but it is not clear to me how to send such instructions to the "Engine" object (which would be step 1 in using this to replace the current engine in Micro-Manager).  There are quite a few classes in the api, but it is not obvious what these are or what they can be used for. 

Some more javadoc, and possibly a few simple examples would go a long way.

**Comment by henrypinkard** [comment]
1) Create an acquisition (`acq`):

https://github.com/micro-manager/AcqEngJ/blob/c2ef88e98b2baf4117d3422fca3a6a37204e1c6d/src/main/java/org/micromanager/acqj/api/Acquisition.java#L76

2) `acq.start();`

3) Call `acq.submitEventIterator(Iterator<AcquisitionEvent> evt)` one or more times

4) `acq.finish()`


`AcquisitionEvent` can be constructed from JSON:

https://github.com/micro-manager/AcqEngJ/blob/c2ef88e98b2baf4117d3422fca3a6a37204e1c6d/src/main/java/org/micromanager/acqj/api/AcquisitionEvent.java#L337

With the specification defined here: 

https://pycro-manager.readthedocs.io/en/latest/apis.html#acquisition-event-specification

**Comment by henrypinkard** [comment]
You never use `Engine` directly after instantiating it. It gets called by `Acquisition`

**Comment by henrypinkard** [comment]
added
