### ISSUE TITLE
AcqEngMetadata: facilitate writing code by either making keys public or adding "has" functions

### ISSUE THREAD

**Issue by nicost** [micro-manager/AcqEngJ#57]
AcqEngMetadata has very nice "get" and "set" functions for most (all?) properties.  However, if the metadata lack the key that one looks for, a RunTimeException will be thrown.  This makes it cumbersome to write code checking for multiple keys, since each "get" function needs to be wrapped in a try-catch block.  Either adding "has" functions for all keys (probably the preferred way), or making the keys public so that the calling code can check itself whether the key is present will make the calling code easier to write and much more performant (as Exceptions are expensive).

**Comment by nicost** [comment]
Kind of related: there are no get and set functions for X_UM_INTENDED (and the Y and Z equivalents).  Should those be added?

**Comment by henrypinkard** [comment]
> there are no get and set functions for X_UM_INTENDED (and the Y and Z equivalents). Should those be added?

Yes

> Either adding "has" functions for all keys (probably the preferred way), or making the keys public so that the calling code can check itself whether the key is present will make the calling code easier to write and much more performant (as Exceptions are expensive).

Agree and either is fine, and I also agree that "has" is the preferred
